config/routes.rb
Rails.application.routes.draw do

  # ========= 管理者(admin)のルーティング ================
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
  }

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :orchestras, only: [:edit, :update, :index]
    # get '/' => 'orchestras#index', as: 'top'
  end
    post 'admin/users/:id' => 'admin/users#update'
  # ========= 利用者(user)のルーティング ================


  # devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    post 'users/orchestra_sign_in', to: 'users/sessions#new_orchestra'

  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    resources :users, only: [:index, :show, :edit, :update]
    resources :orchestras, only: [:new, :create]
    # patch 'events/:id', to: 'events#update',as: 'event'
    resources :events, only: [:index, :show, :new, :edit, :update, :create, :destroy] do
      resources :comments, only: [:create, :destroy]
    end
    resources :tags do
      get 'events', to: 'events#search',as: 'event_search'
    end
    get 'recruitments/confirm/:id' => 'recruitments#confirm', as: 'recruitments_confirm'
    resources :recruitments, only: [:index, :show, :new, :edit, :update, :create, :destroy]
    resources :recruit_users, only: [:create, :index, :destroy, :update]
    resources :recruit_instruments, only: [:create, :new, :index, :update]
    delete 'recruit_instruments/destroy_all' => 'recruit_instruments#destroy_all'
    delete 'recruit_instruments/:id' => 'recruit_instruments#destroy', as: 'destroy_recruit_instrument'
    resources :recruit_relations, only: [:create]
    resources :thank_you_comments, only: [:index, :create, :update]
    get 'thank_you_comment/:id' => 'thank_you_comments#thanks', as: 'thank_you_comment_thanks'
    resources :rooms, only: [:create, :index, :show ]
    get 'search' => 'rooms#search'
    resources :user_rooms, only: [:create, :update]
    resources :chats, only: [:create, :index]
    resources :notifications, only: [:index]
    resources :activities, only: [:index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  mount_uploader :video, VideoUploader
  enum role: { general: 1, orchestra: 2 }#cancancan

  has_many :comments, dependent: :destroy
  has_many :thank_you_comments, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  has_many :user_rooms
  has_many :chats
  has_many :rooms
  has_many :orchestras
  has_many :recruit_users
  has_many :recruitments
  has_many :recruit_relations, dependent: :destroy
  belongs_to :instrument, optional: true
  belongs_to :area, optional: true


  validates :name,  presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i #　←メールアドレスの正規表現
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  #メールアドレスを正規表現のフォームに指定
  validates :area_id,  presence: true
  validates :instrument_id,  presence: true
  # before_save :downcase_email

  def create_notification_join!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'join'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'join'
      )
      notification.save if notification.valid?
    end
  end
  def create_notification_thanks!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'thanks'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'thanks'
      )
      notification.save if notification.valid?
    end
  end

  def create_notification_add_room!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'add_room'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'add_room'
      )
      notification.save if notification.valid?
    end
  end

  def self.guest
    find_or_create_by!(email: 'guest@music.com') do |user|
      user.password = SecureRandom.urlsafe_base64

      user.password_confirmation = user.password
      user.name = 'ゲスト'
      user.instrument_id = 2
      user.area_id =  1
      user.role =  1
      user.introduction = 'Tuningに来て頂きありがとうございます。'
    end
  end
  def self.orchestra
    find_or_create_by!(email: 'guest.orchestra@music.com') do |user|
      user.password = SecureRandom.urlsafe_base64

      user.password_confirmation = user.password
      user.name = 'ゲストオーケストラ'
      user.instrument_id = 1
      user.area_id =  1
      user.role =  2
      user.introduction = 'Tuningに来て頂きありがとうございます。
      オーケストラステータスがあるアカウントなので、イベントだけでなく募集をかけたりトークルームを作成できるようになります。'
    end
  end

  def self.search_user(search)
    if search =~  /^[0-9]+$/
      User.where(['id LIKE ?', "%#{search}%"])
    elsif search !=~  /^[0-9]+$/
      User.where("name LIKE?","%#{search}%")
    else
      @users = User.none
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.includes(:instrument, :area)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_orchestras_path
    else
      render 'show'
    end
  end

  def user_params
    params.permit(:name, :email, :area_id, :instrument_id, :introduction, :profile_image, :role)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
   before_action :check_guest, only: %i[update destroy]

  def check_guest
    if resource.email == 'guest@music.com'
      redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません。'
    end
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :area_id, :instrument_id])
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def new_guest
    user = User.guest
    sign_in user
    redirect_to user_path(current_user.id), notice: 'ゲストユーザーとしてログインしました。'
  end

  def new_orchestra
    user = User.orchestra
    sign_in user
    redirect_to user_path(current_user.id), notice: 'ゲストユーザーとしてログインしました。'
  end


  # GET /resource/sign_in
  def new
    # super
    redirect_to new_user_registration_path
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  
  
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<h2>General users</h2>
  <div class="index_contain_flex_non">
    <% @users.each do |user| %>
      <% if user.role == "general" %>
        <div class="admin-users">
          <%= link_to admin_user_path(user.id) do %>
            <%= attachment_image_tag user, :profile_image, size: "50x50", format: 'jpeg',class: "image", fallback: "public/image/no_image.png" %>
          <% end %>
          <div class="admin-name">
              <p><%= link_to admin_user_path(user.id) do %>
                  <%= user.name %>
                <% end %>
              </p>
              <p>
                <%= user.area.area_name %>
              </p>
              <p>
                <%= user.instrument.instrument_name %>
              </p>
          </div>
        </div>

      <% end %>
    <% end %>

  <h2>Orchestras</h2>
    <% @users.each do |user| %>
      <% if user.role == "orchestra" %>
        <div class="admin-users">
          <%= link_to admin_user_path(user.id) do %>
            <%= attachment_image_tag user, :profile_image, format: 'jpeg',class: "image", fallback: "public/image/no_image.png" %>
          <% end %>
          <div class="admin-name">
              <p><%= link_to admin_user_path(user.id) do %>
                  <%= user.name %>
                <% end %>
              </p>
              <p>
                <%= user.area.area_name %>
              </p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

app/views/admin/users/show.html.erb
<h1 class="gray"><%= @user.name %></h1>

<div class="orchestra-show-contain">
  <div class="orchestra-show">
  <%= attachment_image_tag @user, :profile_image, format: 'jpeg',size: "150x150",class: "image", fallback: "public/image/no_image.png" %>
  </div>

    <div class="orchestra-show-box">
      <div class="orchestra-comment mb10">
        <div class="orchestra-item">
          <p>会員ID</p>
          <p>名前</p>
          <p>エリア</p>
          <p>楽器</p>

          <p>ステータス</p>
        </div>
        <div>
          <p><%= @user.id %></p>
          <p><%= @user.name %></p>
          <p><%= @user.area.area_name %></p>
          <p><%= @user.instrument.instrument_name %></p>
          <p><%= @user.role %></p>
        </div>
      </div>

      <div class="orchestra-form">
        <p class="mb10"><%= @user.introduction %></p>
        <%= form_with(url: admin_user_path, local: true)   do |f| %>
        <div class="pretty p-default  p-fill  p-round p-pulse">
          <%= f.radio_button :role, :general %>
          <div class="state p-success p-info-o">
          　<%= f.label :role, "general"  %>
          </div>
        </div>
        <div class="pretty p-default  p-fill  p-round p-pulse">
          <%= f.radio_button :role, :orchestra %>
          <div class="state p-success p-info-o">
          　<%= f.label :role, "orchestra" %>
          </div>
        </div>
      </div>
      <%= f.submit "更新", id: "btn", class: "btn-size"  %>
      <% end %>
      <div class="orchestra-comment link-space">
        <div class="orchestra-item ">
        <%= link_to admin_orchestras_path do %>
             申請者一覧
        <% end %>
      </div>
        <div>
        <%= link_to admin_users_path do %>
              利用者一覧
        <% end %>

      </div>
      </div>
    </div>
  </div>
</div>