config/routes.rb
Rails.application.routes.draw do

  # ========= 管理者(admin)のルーティング ================
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
  }

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :orchestras, only: [:edit, :update, :index]
    # get '/' => 'orchestras#index', as: 'top'
  end
    post 'admin/users/:id' => 'admin/users#update'
  # ========= 利用者(user)のルーティング ================


  # devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    post 'users/orchestra_sign_in', to: 'users/sessions#new_orchestra'

  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    resources :users, only: [:index, :show, :edit, :update]
    resources :orchestras, only: [:new, :create]
    # patch 'events/:id', to: 'events#update',as: 'event'
    resources :events, only: [:index, :show, :new, :edit, :update, :create, :destroy] do
      resources :comments, only: [:create, :destroy]
    end
    resources :tags do
      get 'events', to: 'events#search',as: 'event_search'
    end
    get 'recruitments/confirm/:id' => 'recruitments#confirm', as: 'recruitments_confirm'
    resources :recruitments, only: [:index, :show, :new, :edit, :update, :create, :destroy]
    resources :recruit_users, only: [:create, :index, :destroy, :update]
    resources :recruit_instruments, only: [:create, :new, :index, :update]
    delete 'recruit_instruments/destroy_all' => 'recruit_instruments#destroy_all'
    delete 'recruit_instruments/:id' => 'recruit_instruments#destroy', as: 'destroy_recruit_instrument'
    resources :recruit_relations, only: [:create]
    resources :thank_you_comments, only: [:index, :create, :update]
    get 'thank_you_comment/:id' => 'thank_you_comments#thanks', as: 'thank_you_comment_thanks'
    resources :rooms, only: [:create, :index, :show ]
    get 'search' => 'rooms#search'
    resources :user_rooms, only: [:create, :update]
    resources :chats, only: [:create, :index]
    resources :notifications, only: [:index]
    resources :activities, only: [:index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_admin_header.html.erb
<nav>
  <ul>
    <li><%= link_to 'log out', destroy_admin_session_path, method: :delete %></li>
    <li><%= link_to 'users', admin_users_path %></li>
    <li><%= link_to 'applications', admin_orchestras_path %></li>
  </ul>
</nav>

app/views/layouts/_header.html.erb
<%= link_to root_path do%><div class="logo"></div><% end %>
  <nav>
    <ul>
      <% if user_signed_in? %>
      <li><%= link_to "log out", destroy_user_session_path, method: :delete %></li>
      <li><%= link_to "top", root_path %></li>
      <li class="has-child"><%= link_to "user", users_path %>
        <ul>
          <li class="has-child"><%= link_to 'mypage', user_path(current_user.id) %>
            <ul>
              <li><%= link_to "thank you", thank_you_comments_path(user: current_user) %></li>
              <li><%= link_to  (notifications_path) do %>通知
                <% if unchecked_notifications.any? %>
                  <span class="orange"><%= unchecked_notifications.count %></span>件
                <% end %>
              <% end %></li>
              <% unless Orchestra.pluck(:user_id).include?(current_user.id) %>
                <% if current_user.role == "genera" %>
                <li><%= link_to "公式楽団申請", new_orchestra_path %></li>
                <% end %>
              <% end %>
            </ul>
          </li>
          <li><%= link_to "トークルーム", rooms_path %></li>
          <li><%= link_to "一覧", users_path %></li>
        </ul>
      </li>

      <li class="has-child"> <%= link_to "find", recruitments_path %>
        <ul>
          <li><%= link_to "募集中", recruitments_path %>
          <li><%= link_to "イベント", events_path %></li>
        </ul>
      </li>
      <% else %>
        <li><%= link_to "start", new_user_registration_path %></li>
        <li><%= link_to "top", root_path %></li>
        <li><%= link_to "about", about_path %></li>
      <% end %>
    </ul>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Tuning</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('favicon.ico') %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <link href=" https://cdn.jsdelivr.net/npm/pretty-checkbox@3.0/dist/pretty-checkbox.min.css">
    <link rel="stylesheet"  href="https://cdn.jsdelivr.net/npm/pretty-checkbox@3.0/dist/pretty-checkbox.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css">
    <% if current_page?(about_path) %>
      <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/multiscroll.js/0.2.2/jquery.multiscroll.css">
    <% end %>
  </head>

  <body data-turbolinks="false">
    <div id="bg">
      <div id="main">

      <span id="header">
      <% if admin_signed_in? %>
        <%= render "layouts/admin_header" %>
      <% else %>
        <%= render "layouts/header" %>
      <% end %>
      </span>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>

      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Modaal/0.4.4/js/modaal.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jscroll/2.4.1/jquery.jscroll.min.js"></script>
    <!--<script src='main.js'></script>-->
    <%= javascript_include_tag "shards" %>
    <% if current_page?(about_path) %>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/multiscroll.js/0.2.2/jquery.multiscroll.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <% end %>
<script>
$(function(){
$('#bg').shards(
  [0,0,0,.9],
  [0,0,0,.8],
	[64,39,23,.8],// 	brown

	20,
	.6,
	1,
	1,
	false
);
});

</script>
  </body>
</html>